<a href="https://colab.research.google.com/github/GersonFabioSilva/pytorch-tutorial/blob/main/Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS


*   a torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   similar to Numpy Arrays, but full of fun things that make them work better on GPUs (vs regular CPUs)

*   default data type of float32
*   more suitable for deep learning than a numpy array


In [ ]:
import torch
import numpy as np

# LISTS

In [ ]:
my_list = [[1,2,3,4,5],
           [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS

In [ ]:
np1 =np.random.rand(3,4)
np1

array([[0.815987  , 0.06924982, 0.62114161, 0.13808882],
       [0.89868764, 0.85845572, 0.29528096, 0.11795683],
       [0.99910493, 0.62144467, 0.63434365, 0.89911376]])

In [ ]:
np1.dtype

dtype('float64')

# TENSORS

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.8107, -0.1873, -0.6455, -0.6701],
        [-0.1458, -0.3422, -0.7241,  0.2696],
        [-0.1248,  0.2421,  0.8560, -0.0467]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8160, 0.0692, 0.6211, 0.1381],
        [0.8987, 0.8585, 0.2953, 0.1180],
        [0.9991, 0.6214, 0.6343, 0.8991]], dtype=torch.float64)

# TENSOR OPERATIONS

In [ ]:
my_torch = torch.arange(10)
my_torch


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#reshape and view
my_torch= my_torch.reshape(2,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#the number of elements must match with the required reshape form, otherwise an error is output

my_torch= my_torch.reshape(2,6)
my_torch


RuntimeError: shape '[2, 6]' is invalid for input of size 10

In [ ]:
# reshape if we don ont know the number of items using -1
my_torch= my_torch.reshape(2,-1)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch= my_torch.reshape(-1,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#with view method

my_torch3 = torch.arange(10)
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch8 = my_torch3.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
#grab slice

my_torch8[:,1]



tensor([1, 3, 5, 7, 9])

In [ ]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

**Tensor MATH Operations**



*   Add, Substract, Multiplyu, Divide, Remainders, Exponents
*   Shorthand and Longhand
*   Reassignment



In [ ]:
import torch


In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
#Addition Longhand

torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
#Subtraction
tensor_a - tensor_b


tensor([-4, -4, -4, -4])

In [ ]:
#subrtraction longhand
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [ ]:
# Multiplication
tensor_a * tensor_b


tensor([ 5, 12, 21, 32])

In [ ]:
#Multiplication longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
#Division
tensor_a / tensor_b



tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
#Division longhand
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
#Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
#Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
#Exponents / power

torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
# another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
#Reassignment
#tensor_a = tensor_a + tensor_b

tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])